Repository CA-G12/Ecommerce-Team-Nine, pull requests merged in 2022-07, with the labels that each got.

#2 complete file structer
  .gitignore
  buyer/cart.css
  buyer/cart.html
  buyer/product.css
  buyer/product.html
  index.html
  js/dom.js
  js/logic.js
  package.json
  seller/product.css
  seller/product.html
  style.css
  test/logic.test.js
Labels: approved

#16 Creating header of all pages
  buyer/cart.css
  buyer/cart.html
  buyer/product.css
  buyer/product.html
  index.html
  seller/product.css
  seller/product.html
  style.css
Labels: approved

#8 Create products list
  buyer/product.css
  buyer/product.html
Labels: approved

#18 make seller section logic
  js/logic.js
  seller/product.css
  seller/product.html
Labels: approved

#17 fixed global font size for all pages
  buyer/cart.css
  seller/product.css
  style.css
Labels: await-review, bugfix

#19 creating and styling filter section
  buyer/product.css
  buyer/product.html
Labels: await-review

#20 11 create product seller page
  img/Group 74.svg
  img/mobile.png
  seller/product.css
  seller/product.html
Labels: approved

#21 progress with seller section
  js/logic.js
  seller/product.css
  seller/product.html
Labels: approved

#25 24 create landing page
  img/website-image.png
  index.html
  seller/product.css
  seller/product.html
  style.css
Labels: approved

#27 26 create functionalty landingpage
  index.html
  js/dom.js
  style.css
Labels: approved

#28 added Readme file
  README.md
Labels: approved

#31 Cart and sorting
  buyer/cart.html
  buyer/product.html
  js/dom.js
  js/logic.js
Labels: await-review

#39 37 fix bug
  index.html
  js/logic.js
Labels: await-review
